export const UPDATE_BOOKS = "UPDATE_BOOKS";

export const ADD_TO_SHELF = "ADD_TO_SHELF";
export const ADD_MULTIPLE_TO_SHELF = "ADD_MULTIPLE_TO_SHELF";
export const REMOVE_FROM_SHELF = "REMOVE_FROM_SHELF";
export const CLEAR_SHELF = "CLEAR_SHELF";
export const UPDATE_SHELF_QUANTITY = "UPDATE_SHELF_QUANTITY";
export const TOGGLE_SHELF = "TOGGLE_SHELF";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const ADD_READBOOK = "ADD_READBOOK";
export const REMOVE_READBOOK = "REMOVE_READBOOK"
















